name: 'enphase dashboard'

services:
    enphase-dashboard:
        build:
            context: ..
            dockerfile: ./enphase-dashboard/Dockerfile
        container_name: enphase-dashboard
        ports:
            - "5000:5000"
        volumes:
            - ./configuration:/app/configuration
        restart: unless-stopped
        environment:
            - FLASK_ENV=production
